import {
  Apartment,
  BeachAccess,
  Bed,
  Cake,
  Cottage,
  Forest,
  Groups,
  Home,
  Hotel,
  House,
  Icecream,
  LocalBar,
  LocalCafe,
  LocalPizza,
  Luggage,
  Park,
  Restaurant,
  TakeoutDining,
} from '@mui/icons-material';

// Configuración por rubro: todo lo que cambia entre una guía y otra vive acá.
// El rubro activo se elige al compilar con VITE_RUBRO (default: alojamientos).
export const GUIAS = {
  alojamientos: {
    rubro: 'alojamientos',
    ruta: '/alojamientos',
    titulo: 'Guía de Alojamientos',
    hero: {
      imagen: '/images/huesped-4.jpg',
      titulo: 'Encontrá tu hospedaje ideal',
      subtitulo: 'Descubrí la mejor oferta de alojamientos en Santa Rosa de Calamuchita',
    },
    ctaPortada: 'Elegí el tipo de alojamiento',
    ctaSubtitulo: 'Todas las opciones disponibles para tu estadía en Santa Rosa de Calamuchita',
    sustantivo: { singular: 'alojamiento', plural: 'alojamientos' },
    volverLogin: 'Volver a la Guía de Alojamientos',
    whatsapp: {
      prefijo: 'la Guía de Alojamientos de Santa Rosa de Calamuchita',
      accion: 'consultar disponibilidad en',
    },
    color: { main: '#00adb7', dark: '#008a92', medio: '#009ca6', light: '#b3eef0' },
    categorias: {
      META: {
        hotel: { nombre: 'Hoteles', icono: Hotel, color: '#00adb7' },
        aparthotel: { nombre: 'Aparthoteles', icono: Apartment, color: '#00adb7' },
        posada: { nombre: 'Posadas', icono: Bed, color: '#ff7300' },
        residencial: { nombre: 'Residenciales', icono: Home, color: '#ff7300' },
        'hostería': { nombre: 'Hosterías', icono: House, color: '#ff7300' },
        hospedaje: { nombre: 'Hospedajes', icono: Bed, color: '#ff7300' },
        hostel: { nombre: 'Hosteles', icono: Groups, color: '#ff7300' },
        departamento: { nombre: 'Departamentos', icono: Apartment, color: '#ff9b00' },
        cabaña: { nombre: 'Cabañas', icono: Park, color: '#7cc100' },
        'apart cabaña': { nombre: 'Apart Cabañas', icono: Park, color: '#7cc100' },
        'complejo de cabañas': { nombre: 'Complejos de Cabañas', icono: Park, color: '#7cc100' },
        colonia: { nombre: 'Colonias', icono: BeachAccess, color: '#b4d006' },
        camping: { nombre: 'Campings', icono: Forest, color: '#b4d006' },
        'casa de alquiler': { nombre: 'Casas', icono: Cottage, color: '#4a6fa5' },
        'agencias de viajes': { nombre: 'Agencias de Viajes', icono: Luggage, color: '#4a6fa5' },
        otros: { nombre: 'Otros alojamientos', icono: Hotel, color: '#4a6fa5' },
      },
      ORDEN: [
        'hotel',
        'aparthotel',
        'posada',
        'hospedaje',
        'hostería',
        'residencial',
        'hostel',
        'colonia',
        'departamento',
        'cabaña',
        'apart cabaña',
        'complejo de cabañas',
        'camping',
        'casa de alquiler',
        'agencias de viajes',
      ],
      MENSAJE: {
        hotel: 'Hotel',
        aparthotel: 'Aparthotel',
        posada: 'Posada',
        residencial: 'Residencial',
        'hostería': 'Hostería',
        hospedaje: 'Hospedaje',
        hostel: 'Hostel',
        departamento: 'Departamento',
        cabaña: 'Cabañas',
        'apart cabaña': 'Apart Cabañas',
        'complejo de cabañas': 'Complejo de Cabañas',
        colonia: 'Colonia',
        camping: 'Camping',
        'casa de alquiler': 'Casa de Alquiler',
        'agencias de viajes': 'Agencia de Viajes',
      },
    },
  },
  gastronomia: {
    rubro: 'gastronomia',
    ruta: '/gastronomia',
    titulo: 'Guía de Gastronomía',
    hero: {
      imagen: '/images/gente-come-4.jpg',
      titulo: 'Encontrá dónde comer',
      subtitulo: 'Descubrí la mejor gastronomía en Santa Rosa de Calamuchita',
    },
    ctaPortada: 'Elegí el tipo de gastronomía',
    ctaSubtitulo: 'Todas las opciones para comer rico en Santa Rosa de Calamuchita',
    sustantivo: { singular: 'local gastronómico', plural: 'locales gastronómicos' },
    volverLogin: 'Volver a la Guía de Gastronomía',
    whatsapp: {
      prefijo: 'la Guía de Gastronomía de Santa Rosa de Calamuchita',
      accion: 'consultar por',
    },
    color: { main: '#e2541b', dark: '#c0391a', medio: '#ff9b00', light: '#fbe0d2' },
    categorias: {
      META: {
        restaurante: { nombre: 'Restaurantes', icono: Restaurant, color: '#e64a19' },
        pizzería: { nombre: 'Pizzerías y Sandwicherías', icono: LocalPizza, color: '#d84315' },
        restobares: { nombre: 'Restobares', icono: LocalBar, color: '#6a1b9a' },
        cafetería: { nombre: 'Casas de Té y Cafeterías', icono: LocalCafe, color: '#795548' },
        heladería: { nombre: 'Heladerías', icono: Icecream, color: '#f06292' },
        'comidas para llevar': { nombre: 'Rotisería y comidas para llevar', icono: TakeoutDining, color: '#00897b' },
        'alfajores y delicias artesanales': { nombre: 'Alfajores y delicias artesanales', icono: Cake, color: '#f06292' },
      },
      ORDEN: [
        'restaurante',
        'pizzería',
        'restobares',
        'cafetería',
        'heladería',
        'comidas para llevar',
        'alfajores y delicias artesanales',
      ],
      MENSAJE: {
        restaurante: 'Restaurante',
        pizzería: 'Pizzería',
        restobares: 'Restobar',
        cafetería: 'Cafetería',
        heladería: 'Heladería',
        'comidas para llevar': 'Rotisería',
        'alfajores y delicias artesanales': 'Especialidad artesanal',
      },
    },
  },
};

const RUBRO_DEFECTO = 'alojamientos';

// Rubro con el que se compiló este sitio (env VITE_RUBRO, default alojamientos)
export const GUIA_ACTIVA = GUIAS[import.meta.env.VITE_RUBRO || RUBRO_DEFECTO] || GUIAS[RUBRO_DEFECTO];